name: fabler
description: A tabler like Dashboard for flutter web.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.1.0

repository: https://github.com/miladimos/fabler

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  beamer: ^1.2.0
  easy_localization: ^3.0.0
  flutter_svg: ^1.0.3
  fabler_icons: ^1.2.0

#  package:
#    git:
#      url:
#      ref:

#  package:
#    path:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: assets/fonts/Schyler-Regular.ttf
  #       - asset: assets/fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: assets/fonts/TrajanPro.ttf
  #       - asset: assets/fonts/TrajanPro_Bold.ttf
  #         weight: 700
